### ISSUE TITLE
What is the repo about?

### ISSUE THREAD

**Issue by Fazel94** [SonyMTKDev/android_device_sony_redwood#1]
Hi, 
Is this repo a LineageOS distribution or is it an official Sony distributed thing?

If it is a LineageOS distro is there link to capabilities implemented and compatibility matrix? since on LineageOS nothing can be found about XA1 Ultra.

**Comment by jmpfbmx** [comment]
Hi
This repo is for building LineageOS
As this device isn't official won't appear at their git org
Thanks!
Regards Jose
